### ISSUE TITLE
Discrepancy in the indent-style

### ISSUE THREAD

**Issue by ankitvijay** [dotnet-foundation/dotnetfoundation-website#102]
The `editor.config` sets the `indent_style` for all files to `tab`. While all / most of the files currently have the `indent_style`  as `space`. It would be good to get it consistent i.e. chose either space or tab.

Currently, this discrepancy makes changes difficult and adds to the confusion as `git diff` and PR diff show inconsistent formatting.

There was a good discussion on [reddit](https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/) why `tab` should be preferred over `space`. Hence, I suggest updating the indent style across the solution to `tab`.

**Comment by onovotny** [comment]
Thanks -- we'll run a linter on it next time we do an update to ensure things are normalized.
