### ISSUE TITLE
OptOut exception 

### ISSUE THREAD

**Issue by Marusyk** [dotnet-foundation/dotnetfoundation-website#108]
The following exception at https://members.dotnetfoundation.org/Profile/OptOut
![Screenshot_2](https://user-images.githubusercontent.com/9221694/67055102-75a57980-f14f-11e9-88cc-f2357d6a5b4b.png)

**Comment by onovotny** [comment]
Is this still happening for you?

**Comment by Marusyk** [comment]
yes

**Comment by onovotny** [comment]
Can you please try again (I expect it to fail but am trying to get a better log)

**Comment by Marusyk** [comment]
Still the same error

**Comment by Marusyk** [comment]
No error anymore
