### ISSUE TITLE
RSS news feed for BLOG is not working on RSS readers

### ISSUE THREAD

**Issue by luisfco** [dotnet-foundation/dotnetfoundation-website#119]
The link:
https://dotnetfoundation.org/Blog
https://dotnetfoundation.org/Blog/rss
Does not return the XML RSS feed

The link in the bottom of page is pointing to:
https://dotnetfoundation.org/**api**/rss

**Comment by onovotny** [comment]
Should be fixed and the link updated to https://dotnetfoundation.org/api/rss
