### ISSUE TITLE
dotnetfoundation.org/News navigation

### ISSUE THREAD

**Issue by andrewcahill** [dotnet-foundation/dotnetfoundation-website#54]
The ‘https://dotnetfoundation.org/News’ navigates to the ‘https://dotnetfoundation.org/Get-Involved’ page, should probably remove this binding url especially as there is a news link in the menu that points to blog ‘https://dotnetfoundation.org/Blog’

**Comment by onovotny** [comment]
This seems to be fixed now, closing.
