### ISSUE TITLE
'Start kicking out code' navigation

### ISSUE THREAD

**Issue by andrewcahill** [dotnet-foundation/dotnetfoundation-website#56]
On home page the ‘Start kicking out code’ section button navigates https://dotnetfoundation.org/# should probably navigate to https://dotnetfoundation.org/About?

**Comment by obsoletenerd** [comment]
My first contribution to a big project on Github, sorry if it's not correct in any way. It seemed like a clear fix to go ahead with due to it being actively broken beforehand.
