### ISSUE TITLE
Https redirection appears not to be working in 'InPrivate' mode in Edge or Incognito in Chrome

### ISSUE THREAD

**Issue by andrewcahill** [dotnet-foundation/dotnetfoundation-website#59]
Check out the below:

![capture](https://user-images.githubusercontent.com/10255671/46395233-c1c87c00-c6fc-11e8-9776-e44eacb2b159.PNG)

**Comment by onovotny** [comment]
I just tried and can't repro. Please reopen if it's still happening. InPrivate/Incogneto shouldn't have any relation to the redirect happening.
