### ISSUE TITLE
Need DNS entry for cla2.dotnetfoundation.org

### ISSUE THREAD

**Issue by ghost** [dotnet-foundation/dotnetfoundation-website#83]
The CLA used to be available at the URL <https://cla2.dotnetfoundation.org>, but now that site is gone.  Since the web doesn't forget and is not amenable to refactoring, and things like [official Mono contributing guide](https://www.mono-project.com/community/contributing/) even link to `cla2`, a DNS entry should be set up to redirect to `cla`.  There is already an HTTP redirect in place.

Steps to reproduce:

1. Visit <https://www.mono-project.com/community/contributing/>
2. Scroll down to "Contributing to Mono"
3. Click ".NET Foundation CLA" link

Actual results:

Browser displays error page.

Expected results:

Browser redirects to <https://cla.dotnetfoundation.org>

**Comment by onovotny** [comment]
The Mono site has been updated and DNS has been updated. That said, the certificate doesn't have cla2.dotnetfoundation.org in it so you'll get an error there.

Closing as that's about all we can do for now, thanks!
