### ISSUE TITLE
Needs a basic README

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet-foundation/dotnetfoundation-website#84]
Attempted to pull the site & build locally but am having to reverse engineer it a little bit to set up the local DB, etc. 

Dropping this here but I hope to add a PR for it. This way I figured if folks are directed to the site, they can see how to easily view changes they make locally, etc.

**Comment by onovotny** [comment]
Closing as dup of #92 (yes, I know this one was here first, the other one is also tracking a contributors.md). A PR is still welcome!

**Comment by SeanKilleen** [comment]
@onovotny totally ok, this fell off my radar anyway. Will hope to pick it up soon.
