### ISSUE TITLE
Scroll Issue

### ISSUE THREAD

**Issue by ashishgehlot** [dotnet-foundation/dotnetfoundation-website#87]
![image](https://user-images.githubusercontent.com/26749354/55557165-df57bc00-5706-11e9-856c-873803ae23ab.png)

On home page: Contribution,COMPANIES etc's count becomes 0 when we scroll up and down multiple times.

**Comment by onovotny** [comment]
I'm closing as not currently reproducing. If it's still happening, please reopen and let us know what browser this is happening with.
