### ISSUE TITLE
"Start kicking out code!" on main page leads to About Foundation page

### ISSUE THREAD

**Issue by karelz** [dotnet-foundation/dotnetfoundation-website#94]
It was a bit surprising that the link/section leads to information about the Foundation, incl. Board members, etc. ... but maybe it is by design

Originally I was confused because Edge Chromium (latest update) does not show the menu on the top of the page at all (so no link to About, etc.), it shows up only if you hover over the menu items. Chrome works fine, so likely browser problem.

@jongalloway

**Comment by onovotny** [comment]
Closing as by-design for now. The about page has links to finding projects, resources, etc.

Will see what happens whenever the site is redesigned again.
